### ISSUE TITLE
Stack trace overriding

### ISSUE THREAD

**Issue by 7rulnik** [aandrewww/winston-transport-sentry-node#2]
There are few ways to pass errors to winston: 

```js
logger.error('look ma ', new Error("it's error"));
logger.error(new Error("it's error"));
```
(see https://github.com/winstonjs/winston/blob/master/examples/errors.js)

Also there is [errors formatter](https://github.com/winstonjs/logform#errors) in logform.

It produces json like this:

```json
{
  "level":"error",
  "message":"it's error",
  "stack":"Error: it's error\n    at Object.<anonymous> (/Users/7rulnik/projects/opensource/winston/examples/errors.js:21:14)\n    at Module._compile (internal/modules/cjs/loader.js:956:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)\n    at internal/main/run_main_module.js:17:11"
}
```

Without this transform, we will just get a pure error instance.

The main problem that previously this transport had been checking for error instance and passing it to sentry or creating a new error with message and stack from log object.

But after #1 it doesn't work because now transport sends new error with the same message. So every new error will have identical stack-traces. 

I believe that we should take it back.

But seems that there was a mistake with stack overriding in ExtendedError. It's more correct.

```js
class ExtendedError extends Error {
  constructor(info) {
    super(info.message);

    this.name = "Error";
    //   this.stack = info.stack || null;
    if (info.stack) {
      this.stack = info.stack;
    }
  }
}
```

I can make a PR if you agree with me

Also I think that we shouldn't send stack as extra data

**Comment by aandrewww** [comment]
@7rulnik Oh, yes I totally согласен :)
Sorry, I checked it poorly after the previous PR and, of course, you can create PR with fixes.

**Comment by joemckie** [comment]
Is this just a case of preventing the transport from creating a new error if the message is an error instance? I can look into this tonight if so. This is a major issue

**Comment by aandrewww** [comment]
@joemckie Yeah, I know. But I don't have free time.

It will be great if you look!

**Comment by aandrewww** [comment]
Fixed. Thanks @cabarnes !

**Comment by aandrewww** [comment]
winston-transport-sentry-node@0.3.0
