### ISSUE TITLE
Request to Publish Version 2.7.1 to NPM

### ISSUE THREAD

**Issue by sorousharzani** [aandrewww/winston-transport-sentry-node#49]
Hello,

I've noticed that the latest version of winston-transport-sentry-node on the NPM registry is 2.7.0, but on GitHub, the package.json indicates a newer version, 2.7.1.

In version 2.7.1, @sentry/node has been moved to peerDependencies which is beneficial for my use case. This change allows for better control over the @sentry/node version used in projects using winston-transport-sentry-node.

Could you please publish version 2.7.1 to the NPM registry?

Thank you for your attention to this matter.

**Comment by aandrewww** [comment]
done
https://www.npmjs.com/package/winston-transport-sentry-node/v/2.7.1
