### ISSUE TITLE
Remove unused lodash dependency

### ISSUE THREAD

**Issue by troxler** [aandrewww/winston-transport-sentry-node#9]
The package.json lists "lodash" as a dependency. But it does not seem to be used anywhere and should thus be removed (unless I'm missing something).

**Comment by aandrewww** [comment]
Thanks for the issue.
Lodash was removed from dependencies.

PS: new version was published
+ winston-transport-sentry-node@0.3.1

**Comment by troxler** [comment]
Thanks, that was quick! :)
